CLUSTAL O(1.2.3) multiple sequence alignment


P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      ------------------------------------------------------------
P50750      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      ------------------------------------------------------------
P21127      ------------------------------------------------------------
Q9NYV4      ------------------------------------------------------------
Q14004      MPSSSDTALGGGGGLSWAEKKLEERRKRRRFLSPQQPPLLLPLLQPQLLQPPPPPPPLLF
O94921      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
Q07002      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      ------------------------------------------------------------
P50750      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      ------------------------------------------------------------
P21127      ------------------------------------------------------------
Q9NYV4      --------------------------------MPNSERHGGKKDGSGGASGTLQPSSGGG
Q14004      LAAPGTAAAAAAAAAASSSCFSPGPPLEVKRLARGKRRAGGRQKRRRG------PRAG--
O94921      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
Q07002      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      ------------------------------------------------------------
P50750      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      ---------------------------------------------------------MGD
P21127      ---------------------------------------------------------MGD
Q9NYV4      SSNSRERHRLVSKHKRHKSKHSKDMGLVTPEAASLGTVIKPLVEYDDISSDSDTFSD--D
Q14004      --QEAEKRRVFSLPQP---------QQDGGGGASSGGGVTPLVEYEDVSSQSEQGLLLGG
O94921      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
Q07002      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      ------------------------------------------------------------
P50750      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      EKDSWK---------------VKTLDEILQ-----------------EKKRRKEQEEKAE
P21127      EKDSWK---------------VKTLDEILQ-----------------EKKRRKEQEEKAE
Q9NYV4      MAFKLD---------------RRENDERRGSDRS----------DRLHKHRHHQHRRSRD
Q14004      ASAATAATAAGGTGGSGGSPASSSGTQRRGEGSERRPRRDRRSSSGRSKERHREHRRRDG
O94921      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
Q07002      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      ------------------------------------------------------------
P50750      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      IKRLKNSDDRDSKRDSLEEGELRDHCMEITIRNSPYRREDSMEDRGEEDDSLAI---KPP
P21127      IKRLKNSDDRDSKRDSLEEGELRDHRMEITIRNSPYRREDSMEDRGEEDDSLAI---KPP
Q9NYV4      LLKAKQTEKEKSQEVSSKSGSMKDRIS-----GSS------KRSNEETDDYGKAQVAKSS
Q14004      QRGGSEA--SKSRSRHSHSGEERAEVA---KSGSS------SSSGGRR-KSASATSSSSS
O94921      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
Q07002      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      ------------------------------------------------------------
P50750      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      QQMSRKEKVHHRKDEKRKEKWKHA------------RVKEREHERRKRHREEQDKARREW
P21127      QQMSRKEKAHHRKDEKRKEKRRHRSHSAEGGKHARVKEKEREHERRKRHREEQDKARREW
Q9NYV4      SKESRSSKLHKEKTRKEREL--KSGHKDRS-KSHRKRETPKSYKTVDSPKRRSRSPHRKW
Q14004      SRKDRDSKAHRS-------------------RTKSSKEPPSAYKEPPKAYREDK------
O94921      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
Q07002      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      ------------------------------------------------------------
P50750      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      ERQKRREMAREHS-RRERDRLEQLERKR--------------ERERKMREQQKEQREQKE
P21127      ERQKRREMAREHS-RRERDRLEQLERKR--------------ERERKMREQQKEQREQKE
Q9NYV4      SDSSKQDDSPSGASYGQDYDLSPSRSHTSSNYDSYKKSPGSTSRRQSVSPPYKEPSAYQS
Q14004      ---------TEPKAYRRRRSLSPLGGRDD--------SPVSHRASQSLR-SRKSP---SP
O94921      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
Q07002      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      ------------------------------------------------------------
P50750      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      RERRAEERRKEREARREVSAHHRTMREDY------SD-------KVKASHWSRSPPR---
P21127      RERRAEERRKEREARREVSAHHRTMREDY------SD-------KVKASHWSRSPPR---
Q9NYV4      STR-S-PSPYSRR-QRSVSPYSRRRSSSYERSGSYSGR---SPSPYGR---RRSSSPFLS
Q14004      AGG-G-SSPYSRRLPRSPSPYSRRRSPSYSRHSSYERGGDVSPSPYSSSSWRRSRSPYS-
O94921      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
Q07002      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      ------------------------------------------------------------
P50750      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      --------PPRERFELGDGRKPGEARPAPAQKPAQLKE-----EKMEER--DLLSDLQDI
P21127      --------PPRERFELGDGRKPGEARPAPAQKPAQLKE-----EKMEER--DLLSDLQDI
Q9NYV4      KRSLSRSPLPSRKSMKSRSRSPAYSRHSSSHSKKKRSSSRSRHSSISPVRLPLNSSLGAE
Q14004      --------PVLRRSGKSRSRSPYSSRHSRSRSRHRLSRSRSRHSSISPSTLTLKSSLAAE
O94921      -----------------------------------------MCDLIEP-------QPAEK
Q96Q40      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
Q07002      ----------------------------------------------------------MI
Q9BWU1      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      ------------------------------------------------------------
P50750      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      SDSERKTSSAESSSAESGSGSEEEE------------------------EEEEE-EEEEG
P21127      SDSERKTSSAESSSAESGSGSEEEE------------------------EEEEE-EEEEG
Q9NYV4      LSRKKKERAAA-AAAAKMDGKESKGSPVFLPRKENSSVEAKDSGLESKKLPRSVKLEKSA
Q14004      LNKNKKARA---AEAARAAEAAKAA--------------------EATKAAEAA--AKAA
O94921      IGKMKKLRRTL-SESFSRIAL-----------------------------------KKDD
Q96Q40      ------------------------------------------------------------
Q00536      MDRMKKIKRQL-SMTLRGGRGIDKT--------------------NGA--PEQIGLDESG
Q00537      ---MKKFKRRL-SLTLRGSQTIDES--------------------LSE-LAEQMTIEENS
Q07002      MNKMKNFKRRF-SLSVPRTETIEES--------------------LAE-FTEQFNQLHNR
Q9BWU1      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      ------------------------------------------------------------
P50750      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      STSEESEEEEE---------------EEEEE----------------------EEETGSN
P21127      STSEESEEEEE---------------EEEEE----------------------EEETGSN
Q9NYV4      PDTELVNVTHLNTEVKNSSDTGKVKLDENSEKHLVKDLKAQGTRDSKPIALKEEIVTPKE
Q14004      KASNTSTPTKGNTETSASASQ--------T--NHVKDVKKIKIEHAP------SPSSGGT
O94921      TTFDEICVTKM-----------------------------S----TR------NCQGMDS
Q96Q40      -MGQELCAKTV-----------------------------QPGCSCY------HCSEGGE
Q00536      GGG-------GS----------------------------DPGEA-P------TRAAPGE
Q00537      SKDNEPIVKNGRPPTSHSMHS--------FLHQYTGSFKKPPLRR-P------HSVIGGS
Q07002      RNENLQLGPLGRDPPQE-------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      ------------------------------------------------------------
P50750      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      ------------------------------------------------------------
P21127      ------------------------------------------------------------
Q9NYV4      TETSEKETPPPLPTIASPPPPLPTTTPPPQTPPLPPLPPIPALPQQPPLPPSQPAFSQVP
Q14004      LKNDKAKTKPP----------LQVTK-------V-----------ENNLIVDKATKKAVI
O94921      V-----I--KP----------L--------------------------------------
Q96Q40      A-----H--SC----------R--------------------------------------
Q00536      LRS--AR--GP----------L--------------------------------------
Q00537      LGSFMAM--PR----------N--------------------------------------
Q07002      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      ------------------------------------------------------------
P50750      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      ------SEEASEQSAEEVSEEEM-------SED-EERENEN--HL-------LVVPES--
P21127      ------SEEASEQSAEEVSEEEM-------SED-EERENEN--HL-------LVVPES--
Q9NYV4      ASSTSTLPPSTHSKTSAVSSQANSQPPVQVSVKTQVSVTAAIPHLKTSTLPPLPLPPLLP
Q14004      VGKESKSAATKE---ESVSLKEK-TKPLTPSIG--AKEKEQHVALVTSTLPPLPLPPMLP
O94921      ----DTIPEDKK---V--------------RVQ--RT---------QSTFDPFEKPAN--
Q96Q40      ----RSQPETTE---AAFKLT---------DLK--EA---S--CS-MTSFHPRGLQAA--
Q00536      ----SSAPEIVH---EDLKMG---------SDG--ES--DQ--AS-ATSSDEVQSPVR--
Q00537      ----GSRLDIVH---ENLKMG---------SDG--ES--DQ--AS-GTSSDEVQSPTG--
Q07002      -----------C---STFSPT---------DSG-------E--EP-G-----QLSPGV--
Q9BWU1      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      ----------------------------------------------------------MD
P50750      ------------------------------------------------------------
Q15131      -------------------------------------MAEPDLECEQIR----LKC----
Q9UQ88      -----RFDRDSGESEEAEEEVG-------EGTPQSSALTEGDYVPDSPA----LLP----
P21127      -----RFDRDSGESEEAEEEVG-------EGTPQSSALTEGDYVPDSPA----LSP----
Q9NYV4      GDDDMDSPKETLPSKPVKKEKEQRTRHLLTDLPLPPELPGGDLSPPDSPEPKAITPPQQP
Q14004      EDKEADSLRGNISVKAVKKEVEKKLRCLLADLPLPPELPGGDDLSKSPEEKK--TATQLH
O94921      -----QVKRV----HSEN-----------------NACINFKTSSTGKESPK--VR----
Q96Q40      -----RAQKFKSKRPRSN-----------------SDCFQEEDLR---------------
Q00536      -----VRMRNHPPRKISTEDINK-RLSLPADIRLPEGYLEKLTLNSPIFDKP--LS----
Q00537      -----VCLRNRIHRRISMEDLNK-RLSLPADIRIPDGYLEKLQINSPPFDQP--MS----
Q07002      -----QFQRRQNQRRFSMEDVSK-RLSLPMDIRLPQEFLQKLQMESPDLPKP--LS----
Q9BWU1      ----------------------------------------------------------MD
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      --------------------------MEDYTKIEKIGEGTYGVVYKGRHKT-TGQ-VVAM
P24941      --------------------------MENFQKVEKIGEGTYGVVYKARNKL-TGE-VVAL
Q00526      --------------------------MDMFQKVEKIGEGTYGVVYKAKNRE-TGQ-LVAL
P11802      ------------------------MATSRYEPVAEIGVGAYGTVYKARDPH-SGH-FVAL
Q00535      --------------------------MQKYEKLEKIGEGTYGTVFKAKNRE-THE-IVAL
Q00534      ----------------M-EKDGLCRADQQYECVAEIGEGAYGKVFKARDLKNGGR-FVAL
P50613      ----------------M-ALDV-KSRAKRYEKLDFLGEGQFATVYKARDKN-TNQ-IVAI
P49336      YDFKVKLSSERER----------VEDLFEYE-GCKVGRGTYGHVYKAKRKDGKDDKDYAL
P50750      -------MAKQYDS----VECPFCDEVSKYEKLAKIGQGTFGEVFKARHRK-TGQ-KVAL
Q15131      IR-KEGFFTVPP----E-HRLGRCRSVKEFEKLNRIGEGTYGIVYRARDTQ-TDE-IVAL
Q9UQ88      IELKQEL--PKY----L-PALQGCRSVEEFQCLNRIEEGTYGVVYRAKDKK-TDE-IVAL
P21127      IELKQEL--PKY----L-PALQGCRSVEEFQCLNRIEEGTYGVVYRAKDKK-TDE-IVAL
Q9NYV4      YKKRPKICCPRYGERRQTESDWGKRCVDKFDIIGIIGEGTYGQVYKAKDKD-TGE-LVAL
Q14004      SKRRPKICGPRYGETKEKDIDWGKRCVDKFDIIGIIGEGTYGQVYKARDKD-TGE-MVAL
O94921      ---------RHSSPSSP-TSPK-FGKADSYEKLEKLGEGSYATVYKGKSKV-NGK-LVAL
Q96Q40      -----------QGFQWR-KSLP-FGAASSYLNLEKLGEGSYATVYKGISRI-NGQ-LVAL
Q00536      ---------RRLRRVSL-SEIG-FGKLETYIKLDKLGEGTYATVYKGKSKL-TDN-LVAL
Q00537      ---------RRSRRASL-SEIG-FGKMETYIKLEKLGEGTYATVYKGRSKL-TEN-LVAL
Q07002      ---------RMSRRASL-SDIG-FGKLETYVKLDKLGEGTYATVFKGRSKL-TEN-LVAL
Q9BWU1      YDFKAKLAAERER----------VEDLFEYE-GCKVGRGTYGHVYKARRKDGKDEKEYAL
Q8IZL9      --------------------------MDQYCILGRIGEGAHGIVFKAKHVE-TGE-IVAL
                                         :     :  * .. *::.           *:

P06493      KKIRLESE---EEGVPSTAIREISLLKE---LRHPN-IVSLQDVLMQ----------DSR
P24941      KKIRLDTE---TEGVPSTAIREISLLKE---LNHPN-IVKLLDVIHT----------ENK
Q00526      KKIRLDLE---MEGVPSTAIREISLLKE---LKHPN-IVRLLDVVHN----------ERK
P11802      KSVRVPNGGGGGGGLPISTVREVALLRRLEAFEHPN-VVRLMDVCATSR-----TDREIK
Q00535      KRVRLDDD---DEGVPSSALREICLLKE---LKHKN-IVRLHDVLHS----------DKK
Q00534      KRVRVQTG---EEGMPLSTIREVAVLRHLETFEHPN-VVRLFDVCTVSR-----TDRETK
P50613      KKIKLGHRSEAKDGINRTALREIKLLQE---LSHPN-IIGLLDAFGH----------KSN
P49336      KQI----E---GTGISMSACREIALLRE---LKHPN-VISLQKVFLSHA--------DRK
P50750      KKVLMENE---KEGFPITALREIKILQL---LKHEN-VVNLIEICRTK--ASPYNRCKGS
Q15131      KKVRMDKE---KDGIPISSLREITLLLR---LRHPN-IVELKEVVVGNH--------LES
Q9UQ88      KRLKMEKE---KEGFPITSLREINTILK---AQHPN-IVTVREIVVGSN--------MDK
P21127      KRLKMEKE---KEGFPITSLREINTILK---AQHPN-IVTVREIVVGSN--------MDK
Q9NYV4      KKVRLDNE---KEGFPITAIREIKILRQ---LIHRS-VVNMKEIVTDKQDALDFKKDKGA
Q14004      KKVRLDNE---KEGFPITAIREIKILRQ---LTHQS-IINMKEIVTDKEDALDFKKDKGA
O94921      KVIRLQE----EEGTPFTAIREASLLKG---LKHAN-IVLLHDIIHT----------KET
Q96Q40      KVISMNA----EEGVPFTAIREASLLKG---LKHAN-IVLLHDIIHT----------KET
Q00536      KEIRLEH----EEGAPCTAIREVSLLKD---LKHAN-IVTLHDIIHT----------EKS
Q00537      KEIRLEH----EEGAPCTAIREVSLLKD---LKHAN-IVTLHDIVHT----------DKS
Q07002      KEIRLEH----EEGAPCTAIREVSLLKN---LKHAN-IVTLHDLIHT----------DRS
Q9BWU1      KQI----E---GTGISMSACREIALLRE---LKHPN-VIALQKVFLSHS--------DRK
Q8IZL9      KKVALRRL---EDGFPNQALREIKALQE---MEDNQYVVQLKAVFPH----------GGG
            * :          *    : **   :       . . :: :                   

P06493      LYLIFEFLSMDLKKYLDSIP------PGQYMDSSLVKSYLYQILQGIVFCHSRRVLHRDL
P24941      LYLVFEFLHQDLKKFMDASA-------LTGIPLPLIKSYLFQLLQGLAFCHSHRVLHRDL
Q00526      LYLVFEFLSQDLKKYMDSTP-------GSELPLHLIKSYLFQLLQGVSFCHSHRVIHRDL
P11802      VTLVFEHVDQDLRTYLDKAP-------PPGLPAETIKDLMRQFLRGLDFLHANCIVHRDL
Q00535      LTLVFEFCDQDLKKYFDSCN--------GDLDPEIVKSFLFQLLKGLGFCHSRNVLHRDL
Q00534      LTLVFEHVDQDLTTYLDKVP-------EPGVPTETIKDMMFQLLRGLDFLHSHRVVHRDL
P50613      ISLVFDFMETDLEVIIKDNS--------LVLTPSHIKAYMLMTLQGLEYLHQHWILHRDL
P49336      VWLLFDYAEHDLWHIIKFHRASKANKKPVQLPRGMVKSLLYQILDGIHYLHANWVLHRDL
P50750      IYLVFDFCEHDLAGLLSNVL--------VKFTLSEIKRVMQMLLNGLYYIHRNKILHRDM
Q15131      IFLVMGYCEQDLASLLENMP--------TPFSEAQVKCIVLQVLRGLQYLHRNFIIHRDL
Q9UQ88      IYIVMNYVEHDLKSLMETMK--------QPFLPGEVKTLMIQLLRGVKHLHDNWILHRDL
P21127      IYIVMNYVEHDLKSLMETMK--------QPFLPGEVKTLMIQLLRGVKHLHDNWILHRDL
Q9NYV4      FYLVFEYMDHDLMGLLESGL--------VHFSEDHIKSFMKQLMEGLEYCHKKNFLHRDI
Q14004      FYLVFEYMDHDLMGLLESGL--------VHFNENHIKSFMRQLMEGLDYCHKKNFLHRDI
O94921      LTLVFEYVHTDLCQYMDKHP--------GGLHPDNVKLFLFQLLRGLSYIHQRYILHRDL
Q96Q40      LTFVFEYMHTDLAQYMSQHP--------GGLHPHNVRLFMFQLLRGLAYIHHQHVLHRDL
Q00536      LTLVFEYLDKDLKQYLDDCG--------NIINMHNVKLFLFQLLRGLAYCHRQKVLHRDL
Q00537      LTLVFEYLDKDLKQYMDDCG--------NIMSMHNVKLFLYQILRGLAYCHRRKVLHRDL
Q07002      LTLVFEYLDSDLKQYLDHCG--------NLMSMHNVKIFMFQLLRGLAYCHHRKILHRDL
Q9BWU1      VWLLFDYAEHDLWHIIKFHRASKANKKPMQLPRSMVKSLLYQILDGIHYLHANWVLHRDL
Q8IZL9      FVLAFEFMLSDLAEVVRHAQ--------RPLAQAQVKSYLQMLLKGVAFCHANNIVHRDL
            . : : .   **   .              .    ::  :   : *: . * . .:***:

P06493      KPQNLLID----DKGTIKLADFGLARAFGI-P---IRVYTHEVVTLWYRSPEVLLGSARY
P24941      KPQNLLIN----TEGAIKLADFGLARAFGV-P---VRTYTHEVVTLWYRAPEILLGCKYY
Q00526      KPQNLLIN----ELGAIKLADFGLARAFGV-P---LRTYTHEVVTLWYRAPEILLGSKFY
P11802      KPENILVT----SGGTVKLADFGLARIYSY-----QMALTPVVVTLWYRAPEVLLQS-TY
Q00535      KPQNLLIN----RNGELKLADFGLARAFGI-P---VRCYSAEVVTLWYRPPDVLFGAKLY
Q00534      KPQNILVT----SSGQIKLADFGLARIYSF-----QMALTSVVVTLWYRAPEVLLQS-SY
P50613      KPNNLLLD----ENGVLKLADFGLAKSFGS-P---NRAYTHQVVTRWYRAPELLFGARMY
P49336      KPANILVMGEGPERGRVKIADMGFARLFNS-PLKPLADLDPVVVTFWYRAPELLLGARHY
P50750      KAANVLIT----RDGVLKLADFGLARAFSLAKNSQPNRYTNRVVTLWYRPPELLLGERDY
Q15131      KVSNLLMT----DKGCVKTADFGLARAYGV-P---VKPMTPKVVTLWYRAPELLLGTTTQ
Q9UQ88      KTSNLLLS----HAGILKVGDFGLAREYGS-P---LKAYTPVVVTQWYRAPELLLGAKEY
P21127      KTSNLLLS----HAGILKVGDFGLAREYGS-P---LKAYTPVVVTLWYRAPELLLGAKEY
Q9NYV4      KCSNILLN----NSGQIKLADFGLARLYNSEE---SRPYTNKVITLWYRPPELLLGEERY
Q14004      KCSNILLN----NRGQIKLADFGLARLYSSEE---SRPYTNKVITLWYRPPELLLGEERY
O94921      KPQNLLIS----DTGELKLADFGLARAKSV-P---SHTYSNEVVTLWYRPPDVLLGSTEY
Q96Q40      KPQNLLIS----HLGELKLADFGLARAKSI-P---SQTYSSEVVTLWYRPPDALLGATEY
Q00536      KPQNLLIN----ERGELKLADFGLARAKSI-P---TKTYSNEVVTLWYRPPDILLGSTDY
Q00537      KPQNLLIN----EKGELKLADFGLARAKSV-P---TKTYSNEVVTLWYRPPDVLLGSSEY
Q07002      KPQNLLIN----ERGELKLADFGLARAKSV-P---TKTYSNEVVTLWYRPPDVLLGSTEY
Q9BWU1      KPANILVMGEGPERGRVKIADMGFARLFNS-PLKPLADLDPVVVTFWYRAPELLLGARHY
Q8IZL9      KPANLLIS----ASGQLKIADFGLARVFSPDG---SRLYTHQVATRWYRAPELLYGARQY
            *  *:*:       * :* .*:*:*:  .             * * *** *: *      

P06493      STPVDIWSIGTIFAELAT-KKPLFHGDS---------EIDQLFRIFRALGTPNNEVWPEV
P24941      STAVDIWSLGCIFAEMVT-RRALFPGDS---------EIDQLFRIFRTLGTPDEVVWPGV
Q00526      TTAVDIWSIGCIFAEMVT-RKALFPGDS---------EIDQLFRIFRMLGTPSEDTWPGV
P11802      ATPVDMWSVGCIFAEMFR-RKPLFCGNS---------EADQLGKIFDLIGLPPEDDWPRD
Q00535      STSIDMWSAGCIFAELANAGRPLFPGND---------VDDQLKRIFRLLGTPTEEQWPSM
Q00534      ATPVDLWSVGCIFAEMFR-RKPLFRGSS---------DVDQLGKILDVIGLPGEEDWPRD
P50613      GVGVDMWAVGCILAELLL-RVPFLPGDS---------DLDQLTRIFETLGTPTEEQWPDM
P49336      TKAIDIWAIGCIFAELLT-SEPIFHCRQEDIKTSNPYHHDQLDRIFNVMGFPADKDWEDI
P50750      GPPIDLWGAGCIMAEMWT-RSPIMQGNT---------EQHQLALISQLCGSITPEVWPNV
Q15131      TTSIDMWAVGCILAELLA-HRPLLPGTS---------EIHQIDLIVQLLGTPSENIWPGF
Q9UQ88      STAVDMWSVGCIFGELLT-QKPLFPGNS---------EIDQINKVFKELGTPSEKIWPGY
P21127      STAVDMWSVGCIFGELLT-QKPLFPGKS---------EIDQINKVFKDLGTPSEKIWPGY
Q9NYV4      TPAIDVWSCGCILGELFT-KKPIFQANL---------ELAQLELISRLCGSPCPAVWPDV
Q14004      TPAIDVWSCGCILGELFT-KKPIFQANQ---------ELAQLELISRICGSPCPAVWPDV
O94921      STCLDMWGVGCIFVEMIQ-GVAAFPGMKD--------IQDQLERIFLVLGTPNEDTWPGV
Q96Q40      SSELDIWGAGCIFIEMFQ-GQPLFPGVSN--------ILEQLEKIWEVLGVPTEDTWPGV
Q00536      STQIDMWGVGCIFYEMAT-GRPLFPGST---------VEEQLHFIFRILGTPTEETWPGI
Q00537      STQIDMWGVGCIFFEMAS-GRPLFPGST---------VEDELHLIFRLLGTPSQETWPGI
Q07002      STPIDMWGVGCIHYEMAT-GRPLFPGST---------VKEELHLIFRLLGTPTEETWPGV
Q9BWU1      TKAIDIWAIGCIFAELLT-SEPIFHCRQEDIKTSNPFHHDQLDRIFSVMGFPADKDWEDI
Q8IZL9      DQGVDLWSVGCIMGELLN-GSPLFPGKN---------DIEQLCYVLRILGTPNPQVWPEL
               :*:*. * *  *:       :                ::  :    *      *   

P06493      ESLQDYKNT-FPK----WKPGSLASHV--KNLD--ENGLDLLSKMLIYDPAKRISGKMAL
P24941      TSMPDYKPS-FPK----WARQDFSKVV--PPLD--EDGRSLLSQMLHYDPNKRISAKAAL
Q00526      TQLPDYKGS-FPK----WTRKGLEEIV--PNLE--PEGRDLLMQLLQYDPSQRITAKTAL
P11802      VSLPRG---AFPP----RGPRPVQSVV--PEME--ESGAQLLLEMLTFNPHKRISAFRAL
Q00535      TKLPDYKPY-PMY----PATTSLVNVV--PKLN--ATGRDLLQNLLKCNPVQRISAEEAL
Q00534      VALPRQ---AFHS----KSAQPIEKFV--TDID--ELGKDLLLKCLTFNPAKRISAYSAL
P50613      CSLPDYVTF--KS----FPGIPLHHIF--SAAG--DDLLDLIQGLFLFNPCARITATQAL
P49336      KKMPEHSTLMKDFRRNTYTNCSLIKYMEKHKVKPDSKAFHLLQKLLTMDPIKRITSEQAM
P50750      DNYELYEKLELVK----GQKRKVKDRL--KAYVRDPYALDLIDKLLVLDPAQRIDSDDAL
Q15131      SKLPLVGQYSLRK----QPYNNLKHKF--P-WL-SEAGLRLLHFLFMYDPKKRATAGDCL
Q9UQ88      SELPVVKKMTFSE----HPYNNLRKRF--GALL-SDQGFDLMNKFLTYFPGRRISAEDGL
P21127      SELPAVKKMTFSE----HPYNNLRKRF--GALL-SDQGFDLMNKFLTYFPGRRISAEDGL
Q9NYV4      IKLPYFNTMKPKK----QYRRRLREEF--SFIP--SAALDLLDHMLTLDPSKRCTAEQTL
Q14004      IKLPYFNTMKPKK----QYRRKLREEF--VFIP--AAALDLFDYMLALDPSKRCTAEQAL
O94921      HSLPHFKPERFTL----YSSKNLRQAW--NKLSYVNHAEDLASKLLQCSPKNRLSAQAAL
Q96Q40      SKLPNYNPEWFPL----PTPRSLHVVW--NRLGRVPEAEDLASQMLKGFPRDRVSAQEAL
Q00536      LSNEEFKTYNYPK----YRAEALLSHA--PRLD--SDGADLLTKLLQFEGRNRISAEDAM
Q00537      SSNEEFKNYNFPK----YKPQPLINHA--PRLD--SEGIELITKFLQYESKKRVSAEEAM
Q07002      TAFSEFRTYSFPC----YLPQPLINHA--PRLD--TDGIHLLSSLLLYESKSRMSAEAAL
Q9BWU1      RKMPEYPTLQKDFRRTTYANSSLIKYMEKHKVKPDSKVFLLLQKLLTMDPTKRITSEQAL
Q8IZL9      TELPDYNKISFKE----QVPMPLEEVL--PDVS--PQALDLLGQFLLYPPHQRIAASKAL
                                  .                 *    :      *  .   :

P06493      NHPYFNDLDNQIKKM---------------------------------------------
P24941      AHPFFQDVTKPVPHLRL-------------------------------------------
Q00526      AHPYFSSPE-PSPAARQ----YV-----LQRFR---------H-----------------
P11802      QHSYLHKDEGNPE-----------------------------------------------
Q00535      QHPYFSDFCPP-------------------------------------------------
Q00534      SHPYFQDLERCKENLDS----HLPPSQNTSELN---------TA----------------
P50613      KMKYFSNRPGPTPGCQL----PRPNCP-VETLK---------EQSNPALA--I----KR-
P49336      QDPYFLEDPLPTSDVFAGCQIPYPKREFLTEEEPDDKGDKKNQQQQQGNNH---------
P50750      NHDFFWSDPMPSDLKGM----LSTHLTSMFEYL--A--PPRRKGSQITQ-----------
Q15131      ESSYFKEKPLPCEP--E----LMPTFPHHRNKR--A--APA-----TSEG----------
Q9UQ88      KHEYFRETPLPIDP--S----MFPTWPAKSEQQ--R--VKRGTSPRPPEG----------
P21127      KHEYFRETPLPIDP--S----MFPTWPAKSEQQ--R--VKRGTSPRPPEG----------
Q9NYV4      QSDFLKDVELSKMAPPD-----LPHWQDCHELW--S--KKRRRQRQSGVVVEEPPPSKTS
Q14004      QCEFLRDVEPSKMPPPD-----LPLWQDCHELW--S--KKRRRQKQMGMTDDVSTIKAP-
O94921      SHEYFSDLPPRLWELTD----MSSIFT-VPNVR---------LQPEAGES----------
Q96Q40      VHDYFSALPSQLYQLPD----EESLFT-VSGVR---------LKPEMCDL----------
Q00536      KHPFFLSLGERIHKLPD----TTSIFA-LKEIQ---------LQKEASLR----------
Q00537      KHVYFRSLGPRIHALPE----SVSIFS-LKEIQ---------LQKDPGFR----------
Q07002      SHSYFRSLGERVHQLED----TASIFS-LKEIQ---------LQKDPGYR----------
Q9BWU1      QDPYFQEDPLPTLDVFAGCQIPYPKREFLNEDDPEEKGDKNQQQQQNQHQQPTAPPQQ--
Q8IZL9      LHQYFFTAPLPAHPSEL----PIPQRL--GGPA---------PKAHPGPPHIH----DF-
               ::                                                       

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      KRTEA-----------LEQGGLPKKLIF--------------------------------
P49336      ------------------------------------------TNGTGHPGNQDSSHTQGP
P50750      ---QS-----------TNQSRNPAT------------------------TNQTEFER---
Q15131      ----Q-----------SKRCKP--------------------------------------
Q9UQ88      ----G-----------LGYSQLGDDDLKETGFHLTTTNQGASAAGPGFSLK---------
P21127      ----G-----------LGYSQLGDDDLKETGFHLTTTNQGASAAGPGFSLK---------
Q9NYV4      RKETTSGTSTEPVKNSSPAPPQPAPGKVESGAG-----DAIGLADITQQLNQSELAV---
Q14004      RKDLSLGLDDS--RTNTPQGVLPSSQLKSQGSS----NVAPVKTGPGQHLNHSELAI---
O94921      --MRA-----------FGKNNSYGKSLSNSKH----------------------------
Q96Q40      --LAS-----------YQKGHHPAQFSKCW------------------------------
Q00536      --SSS-----------MPDSGRPAFRVVDTEF----------------------------
Q00537      --NSS-----------YPETGHGKNRRQSMLF----------------------------
Q07002      --GLA-----------FQQPGRGKNRRQSIF-----------------------------
Q9BWU1      --AAA-----------PPQAPPPQQNSTQTNGTAGGAGAGVGGTGAGLQHSQDSSLNQVP
Q8IZL9      HVDRP-----------LEESLLNPELIRPFIL-----------EG---------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      PLKKVRVVPPTTTSGGL--------IMTSDYQRSNPHAAYPNPG--PSTSQPQSS-----
P50750      ---VF-------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      ----F-------------------------------------------------------
P21127      ----F-------------------------------------------------------
Q9NYV4      ---LLNLLQSQTDLSIPQMAQLLNIHSNPEMQQQLEALNQSISALTEATSQQQDSETMAP
Q14004      ---LLNLLQSKTSVNMADFVQVLNIKVNSETQQQLNKINLPAGILATGEKQTDPSTP-QQ
O94921      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
Q07002      ------------------------------------------------------------
Q9BWU1      PNKKPRLGPSGANSGGP--------VMPSDYQHSSSRLNYQSSV--QGSSQSQST-----
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      -----MGYSATSQQPPQYS--HQTHRY---------------------------------
P50750      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      ------------------------------------------------------------
P21127      ------------------------------------------------------------
Q9NYV4      EES--L-KEAPSA--PVILPSAEQTTLEASSTPADMQNILAVLLSQLMKTQEPAGS---L
Q14004      ESSKPLGGIQPSS--QTIQP-----KVETDAAQAAVQSAFAVLLTQLIKAQQSKQKDVLL
O94921      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
Q07002      ------------------------------------------------------------
Q9BWU1      -----LGYSSSSQQSSQYHPSHQAHRY---------------------------------
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      ------------------------------------------------------------
P50750      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      ------------------------------------------------------------
P21127      ------------------------------------------------------------
Q9NYV4      EENNSDKNSGPQG-----PRRTPTM----------------PQEEAAACPPHILPPEKRP
Q14004      EERE--NGSGHEASLQLRPPPEPSTPVSGQDDLIQHQDMRILELTPEPDRPRILPPDQRP
O94921      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
Q07002      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      ------------------------------------------------------------
P50750      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      ------------------------------------------------------------
P21127      ------------------------------------------------------------
Q9NYV4      PEPPGPPPPPPPPPLVEGDLSSAP------------QELNPAVTAALLQLLSQPEAE--P
Q14004      PEPPEPPP------VTEEDLDYRTENQHVPTTSSSLTDPHAGVKAALLQLLAQHQPQDDP
O94921      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
Q07002      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      ------------------------------------------------------------
P50750      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      ------------------------------------------------------------
P21127      ------------------------------------------------------------
Q9NYV4      PGHLPHEHQALRPMEYSTRPRPNRTYGNTDGPETGFSAIDTDERNSGPALTE------SL
Q14004      KREGGIDYQA--GDTYVSTSDYKDNFGSSSFSSAPYVSNDGLGSSSAPPLERRSFIGNSD
O94921      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
Q07002      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      ------------------------------------------------------------
P50750      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      ------------------------------------------------------------
P21127      ------------------------------------------------------------
Q9NYV4      VQTL-----------------VKNRTFSGSLSHLGESSSYQGTGSVQFPGDQDLRFARVP
Q14004      IQSLDNYSTASSHSGGPPQPSAFSESFPSS--VAGYGDIYLNAGPMLFSGDKDHRFEYSH
O94921      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
Q07002      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      ------------------------------------------------------------
P24941      ------------------------------------------------------------
Q00526      ------------------------------------------------------------
P11802      ------------------------------------------------------------
Q00535      ------------------------------------------------------------
Q00534      ------------------------------------------------------------
P50613      ------------------------------------------------------------
P49336      ------------------------------------------------------------
P50750      ------------------------------------------------------------
Q15131      ------------------------------------------------------------
Q9UQ88      ------------------------------------------------------------
P21127      ------------------------------------------------------------
Q9NYV4      --LALHPVVGQPFLKAEGSSNSVVHAETKLQNYGELGPGTTGASSSGAGLHWGGPTQSSA
Q14004      GPIAVLANSSDPSTGPE--STHPLPAKMHNYNYGGNLQENPSGPSLMHGQTWTSPAQGPG
O94921      ------------------------------------------------------------
Q96Q40      ------------------------------------------------------------
Q00536      ------------------------------------------------------------
Q00537      ------------------------------------------------------------
Q07002      ------------------------------------------------------------
Q9BWU1      ------------------------------------------------------------
Q8IZL9      ------------------------------------------------------------
                                                                        

P06493      -----------------------
P24941      -----------------------
Q00526      -----------------------
P11802      -----------------------
Q00535      -----------------------
Q00534      -----------------------
P50613      -----------------------
P49336      -----------------------
P50750      -----------------------
Q15131      -----------------------
Q9UQ88      -----------------------
P21127      -----------------------
Q9NYV4      YGKLYRGPTRVPPRGGRGRGVPY
Q14004      YSQGYRGHISTSTGRGRGRGLPY
O94921      -----------------------
Q96Q40      -----------------------
Q00536      -----------------------
Q00537      -----------------------
Q07002      -----------------------
Q9BWU1      -----------------------
Q8IZL9      -----------------------
                                   
